sudo: false
branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- 3.7
- 3.6
- 3.5
install:
- pip install --upgrade pip setuptools
- pip install -e .
script:
- true
deploy:
  provider: pypi
  user: datamade.wheelbuilder
  password:
    secure: iqb+U9Qz9AsssPXvHrvpkEU84pOICPUYYEViuY8dHRnCpjkul+6HnPf85W2gmMJAhrAAiw0HSmxPrZHRpUb7vnXX3VDxPbzP8mHC9rsDg/9Fh/lhdZQl29/cXVVWHNqjVDwntawEoHs4xcKFV0Kq1IDTKwhMgG5vnktD/q2wwPjjIoErdCusjvsWMBvJU590jtibVIgZw5GE26Pp1KUbs/GxqJYhDvasOMR35Ei5EcOt4X8ZG2cJUzV01T6h+Gjeo2j18bb6TZpUlgDGYDrEeHC3Ijuzj0xqWCuIlEGHu3HpRXY4b7qaHeWk0Xe4D1TKFRb2mQDy9c0bBhM3L+ryWDcnjyxoV9feE1Bv4sOkgkL7oS2Z+tqcG0VN/M+MIglvwKIXkm80+nXDlQv4rhTvVBu8HN3dz8vrw8DBd5n2J7BhEGKfv1/YXKCsy3hjSfjLult5yW4Vb8+Eku2KP2Zx3LwDIWCxPfwvZtZ61KU/r5Gh+16KsvI9XUzLQ12Qk/hmcyXVFp20I1PHN6UnLXHPWhvofA22W9ytL8rcfKbF8YccmuFoLoFfsTCt3PZ8rYlZmZM+CjRQM0Ke5+UHhP61iCHcxnVjakx7qb4HDn2S/t08HvjNloV/B3ZsRMZciifQFam1WRv98Q7Vmrf9/i3OutIwYF4jM/7xIWEsxF5HDVA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datamade/census_area
  skip_cleanup: 'true'
