sudo: false
branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- 3.7
- 3.6
- 3.5
install:
- pip install --upgrade pip setuptools
- pip install -e .
script:
- true
deploy:
  provider: pypi
  user: datamade.wheelbuilder
  password:
    secure: ORPBaXuF5xf93y4SlXT4SgWvzaG/pPkEqjm5+7TbSKkT67TDUCEOKnu71RQsT9SuxJvNMz/Yl31Es9WPvIy0/RsST3y6wakrPKp9+hyFS+IlDW9lCrjiy8wMGX2D1wuIguT9POs7e9qJvxmR4Lpl1IpANSnLLVcOOhBeA0t1gQ+jzvQl8L8NSf/qthwQPFrnR9ymXm7BHIEVPCv9GYx44tuAYkDFD/VrcSFKeNJmBf2Kp2949DwBXCFdD2m4g5ZRdCqo3WyqqHbVvhPQ/2pIi80zNMWH3d2yhA/ke6T9RnGGIMrCj425U1uCZfRXvhTuL2ny6e3dVQ2S6t4GvAA/leJMoQA0ugXaVp4urW+Vr41jUnUn+IEQuZO5HgJo4eW8FPv8eMFta3rhXbqBWH0xgtFXmO/aQo4mREtDIB9GGcgDkk4Gsvs0ezSIpg2OxnQGGuOG3ZcTopXQSs/E+OrreFqo9lPsbwutIga4Xjw3nYX7QtS2NZ4LzW3SdHfdKEQUKBNjw5zo99yjj4Ym/XF7IJnYAZLqlzyulb9yKJprTxD86aih80wT72vQ0K4o1H9u6I5m31Q2UuYWg/W/t0Fi0IPausjBWZDGohKjddEiPeqBeuModZT4SLXHCuKMnC0AjfKpDRodWAWH6wItcJEg2481N61YQo2TF8xXx6OY/2I=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datamade/census_area
  skip_cleanup: 'true'
