sudo: false
branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- 3.7
- 3.6
- 3.5
install:
- pip install --upgrade pip setuptools
- pip install -e .
script:
- true
deploy:
  provider: pypi
  user: datamade.wheelbuilder
  password:
    secure: pib4AnYzuE1KTA7ZTK3GZ7B6jGmhIDjVBlNdKQbcgBIybpLcE2XGjLs+Jv7t3z5KlhXyAqnZbthLmXSCsgKJGJeeKFtqBDxxZc31B4U8Wtd0/h/BkIk2jaBFJdZOZZvVuEmaESk5izx1x6QsI7YpaylWlB92RIBcxnvhZ9pKAOzG40a5tdufVWHhyyRSh0LolrnE2Ly3Kisvt4aUcwIdp+dt2BGB0BCmp0Awqt97bxxVSANbAepb5a+Hz8ljZj/O7F5KwjfcLDx9DZtfD541ypyp1jcADyZd8dpbWJdNDY5rliSY3pDut+KZrhgLFs/7PuqzgXbipk18bAbiMyBvAUQOBAakWq/mSZANF7swUWIvSMNqPfOKKQUFnAMwPDjssNo2fM0sUTsXSRADx8rKuj8PEjO79cYIVDuuB18H8ZNGTsB3ZtqwnV7K+Q3rKiiHyydfAyNFFW6Mvul3/kjPomJqcxyS1Gk+fq+ixl+YJsbsBuPabqSJrZ6n6olbRs3xH4rQaSsl5MQosfi6lDpBHNcJhUiAv6tBa2Ur45uZyJ5im7dvumcaF0+iWytdn7h5D0Lp0cpsdoHBFFTbEfhMfoR3hdbUKa1mkH9zknSgFkAJGpb5dznqtiMdzgQz1I6vUehqYD1w19d6AEcsBPHzbBf04YUYAL1nxAGXXDQOur4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datamade/census_area
  skip_cleanup: 'true'
