sudo: false
branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- 3.7
- 3.6
- 3.5
install:
- pip install --upgrade pip setuptools
- pip install -e .
script:
- true
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: JhxLHBzaUm4J2nL/0XnwVLDSkKFncJXkvYUiFwTDsf9Hr2MXMOQeml162cdkLl5zSxOSyP93nDOfT9nQk1BRUtlJ2lDDHS6JODAoYRox1x0hPRa0wyGr867V6C7FfGR37kyhSuvEBNriHS6F+wBNblA9FuHEH9iAFwZ5AeHu5N3eBllTYiHbqa+kLR8cqbTokslz41GTJtc9xKoLlzOPUb8C/E4uoZsmQatH+rBpgBciZmTgoT+yqFAhydBcKt8s01Gs17zgJugaColDedp1dhSACsPIYU3s3RgljPWbnQRA5ry3ZS2KdV8BrEq7z5CBucXRPdmTvADQMMYjtuV40kDI3Xo4qNP988kQ7qw4+Ecu1fs6EtVUbm4I9Wc89XzXOSsuQIpkrVZrY973FGjkWAfbPQ4uBcKHpj0PdfAIyVTAcXuPVVUlUyRY8bWdqkVuNXdqQUbM/8JdW8xccHp48AJxFcBtZzqW1Z6byLS58xqRZxYLvqeCGijHpXzkUBYSVI+VhOUmm4WXzWAuRKz0KFlQzKLZUniSDXoBFkQNSaBbbv9mjGeoDqDKrCXQ5s6Qsxt349Bq5ZNk5DbRY1y8GbO1xdC69ICOCtHTjn4eBpcgk1c8+cQntwra4YlcDkWOqXOxaqqrB1hejaRDp2Y9ZuHtGSOcvGMG5BYmhe0qAiw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datamade/census_area
  skip_cleanup: 'true'
